language: rust
rust:
  - 1.42.0  # pinned toolchain for clippy
  - 1.40.0  # minimum supported toolchain (https://github.com/rust-lang/rust/pull/63803)
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

env:
  global:
    - CLIPPY_RUST_VERSION=1.42.0

before_script:
  - bash -c 'if [[ "$TRAVIS_RUST_VERSION" == "$CLIPPY_RUST_VERSION" ]]; then
      rustup component add clippy;
    fi'

script:
  - cargo test
  - cargo test --features cl-legacy
  - bash -c 'if [[ "$TRAVIS_RUST_VERSION" == "$CLIPPY_RUST_VERSION" ]]; then
      cargo clippy -- -D warnings;
    fi'
  - bash -c 'if [[ "$TRAVIS_RUST_VERSION" == "$CLIPPY_RUST_VERSION" ]]; then
      cargo clippy --features cl-legacy -- -D warnings;
    fi'
